export const managerPermission = (permission) => {
  const permissionEng = [
    {
      id: 1,
      value: "customerAdd",
      label: "Customer Add",
      isChecked: permission?.customerAdd,
    },
    {
      id: 2,
      value: "customerEdit",
      label: "Customer Edit",
      isChecked: permission?.customerEdit,
    },
    {
      id: 3,
      value: "customerActivate",
      label: "Customer Activate",
      isChecked: permission?.customerActivate,
    },
    {
      id: 4,
      value: "customerDeactivate",
      label: "Customer Deactivate",
      isChecked: permission?.customerDeactivate,
    },
    {
      id: 5,
      value: "customerDelete",
      label: "Customer Delete",
      isChecked: permission?.customerDelete,
    },
    {
      id: 6,
      value: "billEdit",
      label: "Update Bill",
      isChecked: permission?.billEdit,
    },
    {
      id: 7,
      value: "monthlyFeeEdit",
      label: "Update Monthly Fee",
      isChecked: permission?.monthlyFeeEdit,
    },
    {
      id: 8,
      value: "sendSMS",
      label: "SMS Board",
      isChecked: permission?.sendSMS,
    },
    {
      id: 10,
      value: "billPosting",
      label: "Bill Posting",
      isChecked: permission?.billPosting,
    },
    {
      id: 11,
      value: "collectorAdd",
      label: "Collector Add",
      isChecked: permission?.collectorAdd,
    },
    {
      id: 12,
      value: "collectorEdit",
      label: "Collector Update",
      isChecked: permission?.collectorEdit,
    },
    {
      id: 13,
      value: "viewCollectorReport",
      label: "View Collector Report",
      isChecked: permission?.viewCollectorReport,
    },
    {
      id: 14,
      value: "readMessageLog",
      label: "See Message Log",
      isChecked: permission?.readMessageLog,
    },
    // {
    //   id: 15,
    //   value: "bulkAreaEdit",
    //   label: "Bulk Area Edit",
    //   isChecked: permission?.bulkAreaEdit,
    // },
    // {
    //   id: 16,
    //   value: "bulkStatusEdit",
    //   label: "Bulk Status Edit",
    //   isChecked: permission?.bulkStatusEdit,
    // },
    // {
    //   id: 17,
    //   value: "bulkBillingCycleEdit",
    //   label: "Bulk BillingCycle Edit",
    //   isChecked: permission?.bulkBillingCycleEdit,
    // },
    // {
    //   id: 18,
    //   value: "bulkPromiseDateEdit",
    //   label: "Bulk Promise Date Edit",
    //   isChecked: permission?.bulkPromiseDateEdit,
    // },
    // {
    //   id: 19,
    //   value: "bulkAutoDisableEdit",
    //   label: "Bulk Auto Disable Edit",
    //   isChecked: permission?.bulkAutoDisableEdit,
    // },
    // {
    //   id: 20,
    //   value: "bulkPackageEdit",
    //   label: "Bulk Package Edit",
    //   isChecked: permission?.bulkPackageEdit,
    // },
    // {
    //   id: 21,
    //   value: "bulkTransferToReseller",
    //   label: "Bulk Customer Transfer To Reseller",
    //   isChecked: permission?.bulkTransferToReseller,
    // },
    // {
    //   id: 22,
    //   value: "bulkCustomerDelete",
    //   label: "Bulk Customer Delete",
    //   isChecked: permission?.bulkCustomerDelete,
    // },
    //   id: 22,
    //   value: "updateCustomerBalance",
    //   label: "Update Customer Balance",
    //   isChecked: permission?.updateCustomerBalance,
    // },
  ];

  const permissionBangla = [
    {
      id: 1,
      value: "customerAdd",
      label: "গ্রাহক সংযোগ",
      isChecked: permission?.customerAdd,
    },
    {
      id: 2,
      value: "customerEdit",
      label: "গ্রাহক আপডেট",
      isChecked: permission?.customerEdit,
    },
    {
      id: 3,
      value: "customerActivate",
      label: "গ্রাহক এক্টিভেট",
      isChecked: permission?.customerActivate,
    },
    {
      id: 4,
      value: "customerDeactivate",
      label: "গ্রাহক বন্ধ",
      isChecked: permission?.customerDeactivate,
    },
    {
      id: 5,
      value: "customerDelete",
      label: "গ্রাহক ডিলিট",
      isChecked: permission?.customerDelete,
    },
    {
      id: 6,
      value: "billEdit",
      label: "বিল আপডেট",
      isChecked: permission?.billEdit,
    },
    {
      id: 7,
      value: "monthlyFeeEdit",
      label: "মাসিক ফি আপডেট",
      isChecked: permission?.monthlyFeeEdit,
    },
    {
      id: 8,
      value: "sendSMS",
      label: "ম্যাসেজ বোর্ড",
      isChecked: permission?.sendSMS,
    },
    {
      id: 10,
      value: "billPosting",
      label: "বিল পোস্টিং",
      isChecked: permission?.billPosting,
    },
    {
      id: 11,
      value: "collectorAdd",
      label: "কালেক্টর অ্যাড",
      isChecked: permission?.collectorAdd,
    },
    {
      id: 12,
      value: "collectorEdit",
      label: "কালেক্টর আপডেট",
      isChecked: permission?.collectorEdit,
    },
    {
      id: 13,
      value: "viewCollectorReport",
      label: "কালেক্টর রিপোর্ট দেখবে",
      isChecked: permission?.viewCollectorReport,
    },
    {
      id: 14,
      value: "readMessageLog",
      label: "চেক মেসেস লগ",
      isChecked: permission?.readMessageLog,
    },
    // {
    //   id: 15,
    //   value: "bulkAreaEdit",
    //   label: "বাল্ক এরিয়া এডিট",
    //   isChecked: permission?.bulkAreaEdit,
    // },
    // {
    //   id: 16,
    //   value: "bulkStatusEdit",
    //   label: "বাল্ক স্ট্যাটাস এডিট",
    //   isChecked: permission?.bulkStatusEdit,
    // },
    // {
    //   id: 17,
    //   value: "bulkBillingCycleEdit",
    //   label: "বাল্ক বিলিং সাইকেল এডিট",
    //   isChecked: permission?.bulkBillingCycleEdit,
    // },
    // {
    //   id: 18,
    //   value: "bulkPromiseDateEdit",
    //   label: "বাল্ক প্রমিজ ডেট এডিট",
    //   isChecked: permission?.bulkPromiseDateEdit,
    // },
    // {
    //   id: 19,
    //   value: "bulkAutoDisableEdit",
    //   label: "বাল্ক আটো ডিজেবল এডিট",
    //   isChecked: permission?.bulkAutoDisableEdit,
    // },
    // {
    //   id: 20,
    //   value: "bulkPackageEdit",
    //   label: "বাল্ক প্যকেজ এডিট",
    //   isChecked: permission?.bulkPackageEdit,
    // },
    // {
    //   id: 21,
    //   value: "bulkTransferToReseller",
    //   label: "বাল্ক রিসেলার গ্রাহক ট্রান্সফার",
    //   isChecked: permission?.bulkTransferToReseller,
    // },
    // {
    //   id: 22,
    //   value: "bulkCustomerDelete",
    //   label: "বাল্ক গ্রাহক ডিলিট",
    //   isChecked: permission?.bulkCustomerDelete,
    // },
    // {
    //   id: 23,
    //   value: "updateCustomerBalance",
    //   label: "গ্রাহক ব্যালেন্স এডিট",
    //   isChecked: permission?.updateCustomerBalance,
    // },
  ];

  if (localStorage.getItem("netFee:lang") === "bn") return permissionBangla;
  return permissionEng;
};
