export const RPD = [
  { id: 1, type: "text", label: "নাম", name: "name" },
  { id: 1, type: "text", label: "মোবাইল", name: "mobile" },
  { id: 1, type: "text", label: "এড্রেস", name: "address" },
  { id: 1, type: "email", label: "ইমেইল", name: "email" },
  { id: 1, type: "text", label: "NID নম্বর", name: "nid" },
  { id: 1, type: "text", label: "ওয়েবসাইট", name: "website" },
  // { id: 1, type: "text", label: "রিচার্জ ব্যালান্স", name: "rechargeBalance" },
  // { id: 1, type: "text", label: "SMS রেট", name: "smsRate" },
  // { id: 1, type: "text", label: "Commission রেট", name: "commissionRate" },
  // { id: 1, type: "text", label: "রেফারেন্স নাম", name: "refName" },
  // { id: 1, type: "text", label: "রেফারেন্স মোবাইল", name: "refMobile" },
];

export const RADIO = [
  { id: 2, label: "এক্টিভ", value: "active" },
  { id: 3, label: "ইনএক্টিভ", value: "inactive" },
];

// export const resellerPermissionEng = [
//   { id: 1, label: "Customer Add", value: "customerAdd", isChecked: false },
//   { id: 2, label: "Customer Edit", value: "customerEdit", isChecked: false },
//   {
//     id: 3,
//     label: "Edit monthly Fee",
//     value: "monthlyFeeEdit",
//     isChecked: false,
//   },

//   {
//     id: 4,
//     label: "Package Edit",
//     value: "customerMikrotikPackageEdit",
//     isChecked: false,
//   },
//   {
//     id: 5,
//     label: "Status Edit",
//     value: "customerStatusEdit",
//     isChecked: false,
//   },
//   {
//     id: 6,
//     label: "Auto Disabled",
//     value: "customerAutoDisableEdit",
//     isChecked: false,
//   },
//   {
//     id: 7,
//     label: "Area Delete",
//     value: "areaDelete",
//     isChecked: false,
//   },
//   // {
//   //   id: 8,
//   //   label: "Area Add",
//   //   value: "areaAdd",
//   //   isChecked: false,
//   // },
//   {
//     id: 9,
//     label: "Bulk Area Edit",
//     value: "bulkAreaEdit",
//     isChecked: false,
//   },
//   {
//     id: 10,
//     label: "Bulk Status Edit",
//     value: "bulkCustomerStatusEdit",
//     isChecked: false,
//   },
//   {
//     id: 11,
//     label: "Bulk BillingCycle Edit",
//     value: "bulkCustomerBillingCycleEdit",
//     isChecked: false,
//   },
//   {
//     id: 12,
//     label: "Bulk Customer Recharge",
//     value: "bulkCustomerRecharge",
//     isChecked: false,
//   },
//   {
//     id: 13,
//     label: "Instant Recharge Bill Print",
//     value: "instantRechargeBillPrint",
//     isChecked: false,
//     disable: false,
//   },
//   {
//     id: 14,
//     label: "Billing Cycle Edit",
//     value: "billingCycleEdit",
//     isChecked: false,
//     disabled: false,
//   },
//   {
//     id: 15,
//     label: "Single Customer Number Edit",
//     value: "singleCustomerNumberEdit",
//     isChecked: false,
//     disabled: false,
//   },
//   {
//     id: 16,
//     label: "Daily Recharge Feature",
//     value: "dailyRechargeFeature",
//     isChecked: false,
//     disabled: false,
//   },
//   {
//     id: 17,
//     label: "Minus Balance",
//     value: "minusBalance",
//     isChecked: false,
//     disabled: false,
//   },
//   {
//     id: 18,
//     label: "Customer Automatic Connection OnOff",
//     value: "customerAutomaticConnectionOnOff",
//     isChecked: false,
//     disabled: false,
//   },
//   {
//     id: 19,
//     label: "Add Customer With Mobile Number",
//     value: "addCustomerWithMobile",
//     isChecked: false,
//     disabled: false,
//   },
// ];

// export const resellerPermissionBan = [
//   { id: 1, label: "কাস্টমার অ্যাড", value: "customerAdd", isChecked: false },
//   { id: 2, label: "কাস্টমার এডিট", value: "customerEdit", isChecked: false },
//   { id: 3, label: "মাসিক ফি এডিট", value: "monthlyFeeEdit", isChecked: false },

//   {
//     id: 4,
//     label: "প্যাকেজ এডিট",
//     value: "customerMikrotikPackageEdit",
//     isChecked: false,
//   },
//   {
//     id: 5,
//     label: "স্টাটাস এডিট",
//     value: "customerStatusEdit",
//     isChecked: false,
//   },
//   {
//     id: 6,
//     label: "অটো ডিসেবল",
//     value: "customerAutoDisableEdit",
//     isChecked: false,
//   },
//   {
//     id: 7,
//     label: "এরিয়া ডিলিট",
//     value: "areaDelete",
//     isChecked: false,
//   },
//   // {
//   //   id: 8,
//   //   label: "এড এরিয়া",
//   //   value: "areaAdd",
//   //   isChecked: false,
//   // },
//   {
//     id: 9,
//     label: "বাল্ক এরিয়া এডিট",
//     value: "bulkAreaEdit",
//     isChecked: false,
//   },
//   {
//     id: 10,
//     label: "বাল্ক স্ট্যাটাস এডিট",
//     value: "bulkCustomerStatusEdit",
//     isChecked: false,
//   },
//   {
//     id: 11,
//     label: "বাল্ক বিলিং সাইকেল এডিট",
//     value: "bulkCustomerBillingCycleEdit",
//     isChecked: false,
//   },
//   {
//     id: 12,
//     label: "বাল্ক গ্রাহক রিচার্জ",
//     value: "bulkCustomerRecharge",
//     isChecked: false,
//   },
//   {
//     id: 13,
//     label: "ইনস্ট্যান্ট রিচার্জ বিল প্রিন্ট",
//     value: "instantRechargeBillPrint",
//     isChecked: false,
//     disable: false,
//   },
//   {
//     id: 14,
//     label: "বিলিং সাইকেল এডিট",
//     value: "billingCycleEdit",
//     isChecked: false,
//     disabled: false,
//   },
//   {
//     id: 15,
//     label: "সিঙ্গেল কাস্টমার নম্বর এডিট",
//     value: "singleCustomerNumberEdit",
//     isChecked: false,
//     disabled: false,
//   },
//   {
//     id: 16,
//     label: "দৈনিক রিচার্জ ফিচার",
//     value: "dailyRechargeFeature",
//     isChecked: false,
//     disabled: false,
//   },
//   {
//     id: 17,
//     label: "মাইনাস ব্যালান্স",
//     value: "minusBalance",
//     isChecked: false,
//     disabled: false,
//   },
//   {
//     id: 18,
//     label: "গ্রাহক অটোমেটিক সংযোগ অনঅফ",
//     value: "customerAutomaticConnectionOnOff",
//     isChecked: false,
//     disabled: false,
//   },
//   {
//     id: 19,
//     label: "মোবাইল নাম্বার সহ কাস্টমার অ্যাড",
//     value: "addCustomerWithMobile",
//     isChecked: false,
//     disabled: false,
//   },

//   // { id: 3, label: "কাস্টমার ডিলিট", value: "customerDelete", isChecked: false },

//   // { id: 5, label: "বিল এডিট", value: "billEdit", isChecked: false },
//   // { id: 7, label: "বিল পোস্টিং", value: "billPosting", isChecked: false },
//   // { id: 8, label: "একাউন্টস", value: "accounts", isChecked: false },
//   // { id: 9, label: "ইনভেন্টরি", value: "inventory", isChecked: false },
//   // { id: 10, label: "ওয়েব লগইন", value: "webLogin", isChecked: false },
//   // {
//   //   id: 11,
//   //   label: "কাস্টমার লিস্ট দেখতে পারবে",
//   //   value: "viewCustomerList",
//   //   isChecked: false,
//   // },
//   // { id: 12, label: "সেন্ড SMS", value: "sendSMS", isChecked: false },
//   // {
//   //   id: 13,
//   //   label: "কাস্টমার এক্টিভ",
//   //   value: "customerActivate",
//   //   isChecked: false,
//   // },
//   // {
//   //   id: 14,
//   //   label: "কাস্টমার ডিএক্টিভ",
//   //   value: "customerDeactivate",
//   //   isChecked: false,
//   // },
//   // { id: 15, label: "প্রিন্ট", value: "print", isChecked: false },
//   // { id: 16, label: "কালেক্টর অ্যাড", value: "collectorAdd", isChecked: false },
//   // { id: 17, label: "কালেক্টর এডিট", value: "collectorEdit", isChecked: false },
//   // {
//   //   id: 18,
//   //   label: "সব রিপোর্ট দেখতে পারবে",
//   //   value: "viewTotalReport",
//   //   isChecked: false,
//   // },
//   // {
//   //   id: 19,
//   //   label: "কালেক্টর রিপোর্ট দেখতে পারবে",
//   //   value: "viewCollectorReport",
//   //   isChecked: false,
//   // },
//   // { id: 12, label: "ফাইল আপলোড", value: "fileExport", isChecked: false },
// ];
