export const inputs = [
  {
    id: 1,
    name: 'company',
    type: 'text',
    errorMessage: 'তিনটার বেশি অক্ষর থাকতে হবে, স্পেস দেয়া যাবে না',
    label: 'কোম্পানির নাম (ইংলিশে) ',
    pattern: '^(?=.*[a-z])(?!-|.*-$|.*-.*-)[a-zd-]{3,22}$',
    required: true,
  },
  {
    id: 2,
    name: 'name',
    type: 'text',
    errorMessage: 'তিনটার বেশি অক্ষর থাকতে হবে, স্পেস দেয়া যাবে না',
    label: 'নাম (ইংলিশে)',
    pattern: '^(?=.*[a-z])(?!-|.*-$|.*-.*-)[a-zd-]{3,22}$',
    required: true,
  },
  {
    id: 3,
    name: 'mobile',
    type: 'text',
    errorMessage: 'শুরুতে 01 থাকবে আর  এগারোটা অক্ষর থাকতে হবে ',
    label: 'মোবাইল (ইংলিশে)',
    pattern: '(?:\\+88|88)?(01[3-9]\\d{8})',
    required: true,
  },
  {
    id: 4,
    name: 'email',
    type: 'email',
    errorMessage: 'সঠিক ইমেইল দিন ',
    pattern: '^[^s@]+@[^s@]+.[^s@]+$',
    label: 'ইমেইল ',
    required: true,
  },
  {
    id: 5,
    name: 'reference',
    type: 'text',
    label: 'রেফারেন্স ( জরুরী না )',
    disabled: true,
  },
  {
    id: 6,
    name: 'pack',
    type: 'text',
    errorMessage: '',
    pattern: 'Gold',
    required: true,
  },
]
