const pakage = [
  {
    packageName: "Basic",
    packageNameBangla: "বেসিক",
    subPakage: [
      {
        id: "0",
        subPackageName: "P1",
        customer: "300",
        installation: "4000",
        monthly: "1000",
      },
      {
        id: "1",
        subPackageName: "P2",
        customer: "500",
        installation: "5000",
        monthly: "1500",
      },
      {
        id: "2",
        subPackageName: "P3",
        customer: "700",
        installation: "6000",
        monthly: "2000",
      },
      {
        id: "3",
        subPackageName: "P4",
        customer: "1000",
        installation: "7000",
        monthly: "2500",
      },
      {
        id: "4",
        subPackageName: "P5",
        customer: "1250",
        installation: "8000",
        monthly: "3000",
      },
      {
        id: "5",
        subPackageName: "P6",
        customer: "1500",
        installation: "10000",
        monthly: "3500",
      },
      {
        id: "6",
        subPackageName: "P7",
        customer: "2000",
        installation: "12500",
        monthly: "4000",
      },
      {
        id: "7",
        subPackageName: "P8",
        customer: "2500",
        installation: "15000",
        monthly: "4800",
      },
      {
        id: "8",
        subPackageName: "P9",
        customer: "3000",
        installation: "18000",
        monthly: "5500",
      },
    ],
  },
  {
    packageName: "Standard",
    packageNameBangla: "স্ট্যান্ডার্ড",
    subPakage: [
      {
        id: "9",
        subPackageName: "P1",
        customer: "300",
        installation: "6000",
        monthly: "1500",
      },
      {
        id: "10",
        subPackageName: "P2",
        customer: "500",
        installation: "7500",
        monthly: "2250",
      },
      {
        id: "11",
        subPackageName: "P3",
        customer: "700",
        installation: "9000",
        monthly: "3000",
      },
      {
        id: "12",
        subPackageName: "P4",
        customer: "1000",
        installation: "10500",
        monthly: "3750",
      },
      {
        id: "13",
        subPackageName: "P5",
        customer: "1250",
        installation: "12000",
        monthly: "4500",
      },
      {
        id: "14",
        subPackageName: "P6",
        customer: "1500",
        installation: "15000",
        monthly: "5250",
      },
      {
        id: "15",
        subPackageName: "P7",
        customer: "2000",
        installation: "18750",
        monthly: "6000",
      },
      {
        id: "16",
        subPackageName: "P8",
        customer: "2500",
        installation: "22500",
        monthly: "7200",
      },
      {
        id: "17",
        subPackageName: "P9",
        customer: "3000",
        installation: "27000",
        monthly: "8250",
      },
    ],
  },
  // {
  //   packageName: "Premium",
  //   packageNameBangla: "প্রিমিয়াম",
  //   subPakage: [
  //     {
  //       id: "18",
  //       subPackageName: "P1",
  //       customer: "300",

  //       installation: "8000",
  //       monthly: "2000",
  //     },
  //     {
  //       id: "19",
  //       subPackageName: "P2",
  //       customer: "500",

  //       installation: "10000",
  //       monthly: "3000",
  //     },
  //     {
  //       id: "20",
  //       subPackageName: "P3",
  //       customer: "700",

  //       installation: "12000",
  //       monthly: "4000",
  //     },
  //     {
  //       id: "21",
  //       subPackageName: "P4",
  //       customer: "1000",
  //       installation: "14000",
  //       monthly: "5000",
  //     },
  //     {
  //       id: "22",
  //       subPackageName: "P5",
  //       customer: "1250",
  //       installation: "16000",
  //       monthly: "6000",
  //     },
  //     {
  //       id: "23",
  //       subPackageName: "P6",
  //       customer: "1500",
  //       installation: "20000",
  //       monthly: "7000",
  //     },
  //     {
  //       id: "24",
  //       subPackageName: "P7",
  //       customer: "2000",
  //       installation: "25000",
  //       monthly: "8000",
  //     },
  //     {
  //       id: "25",
  //       subPackageName: "P8",
  //       customer: "2500",
  //       installation: "30000",
  //       monthly: "9600",
  //     },
  //     {
  //       id: "26",
  //       subPackageName: "P9",
  //       customer: "3000",
  //       installation: "36000",
  //       monthly: "11000",
  //     },
  //   ],
  // },
];

export default pakage;
